// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xuuawjlsgfmfkysjvmzu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh1dWF3amxzZ2ZtZmt5c2p2bXp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzMDAyNzYsImV4cCI6MjA2Mzg3NjI3Nn0.7VOrV-5QiJVkXECainolLOZpImHL1eVLI9dvLO7s3ig";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);